version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: virtu360-postgres-dev

    environment:
      POSTGRES_DB: virtu360_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: virtu360-app-dev

    depends_on:
      - postgres

    env_file:
      - .env.dev

    ports:
      - "8080:8080"

volumes:
  postgres_dev_data: