# =========================================================
# DEVELOPMENT PROFILE
# =========================================================

# =========================================================
# DATABASE
# =========================================================
spring.datasource.url=${DEV_DB_URL:jdbc:postgresql://localhost:5432/virtu360_dev}
spring.datasource.username=${DEV_DB_USERNAME:postgres}
spring.datasource.password=${DEV_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================================================
# LOGGING
# =========================================================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =========================================================
# ACTUATOR
# =========================================================
management.endpoints.web.exposure.include=*

# =========================================================
# DEVTOOLS
# =========================================================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true